// Code generated by ef. DO NOT EDIT.

package {{.TableName.SnakeName}}_model

type {{.TableName.PascalName}} struct {
  {{range .Fields}}{{.FieldName.PascalName}} {{.Type}} `gorm:"column:{{.FieldName.SnakeName}}"`
  {{end}}
}

func (*{{.TableName.PascalName}}) TableName() string {
  return "{{.TableName.SnakeName}}"
}